import time
#Delimiter
print('\n------------------------')
time.sleep(.1)
print('\n*DING DONG DING DONG*')
time.sleep(1)
print('\n\"..........\"')
time.sleep(2)
print('\n\"uuuuurrrrrrrrrggg....\"')
time.sleep(2)
print('\n[You wake up from the sound of an alarm bell.]')
time.sleep(1)
print('\n[You look around and find yourself in a dark room.]')
time.sleep(1)
print('\"Where am I? What is this place? What am I doing here?\"')
time.sleep(2)
print('[You feel your')